### ISSUE TITLE
Debugging the running kernel

### ISSUE THREAD

**Issue by FrankRay78** [Rodmatronic/CatK#2]
Hello, I'd create a discussion, or send an email, if I had the ability...

I was just wondering if, and how, you go about debugging the running kernel.

**Comment by Rodmatronic** [comment]
Hello FrankRay78! I actually have not been debugging the kernel until very recently, I do so by doing this:

`qemu-system-x86_64 -s -S -kernel /path/to/catkernel.bin`

`gdb /path/to/catkernel.bin`

(in gdb)
`set arch i386:x86-64`
`target remote localhost:1234`

Now you can use b function_name or b function_name:line_number to debug

**Comment by irixaligned** [comment]
we've got a discord now where you can discuss stuff like this further, and the rewrite (soon to be main) has debugging instructions for both lldb and gdb, so i'm gonna close this for now
